import type { ReactNode } from "react";

export const STREAM_STYLE = {
  MEAL: {
    label: "Meal",
    text: "text-meal",
    bg: "bg-meal",
    soft: "bg-meal-soft",
    // Older/limited emoji font sets are missing U+1F37D (plate); the apple is
    // in Emoji 1.0 and renders everywhere.
    icon: "🍎",
  },
  WATER: {
    label: "Hydration",
    text: "text-water",
    bg: "bg-water",
    soft: "bg-water-soft",
    icon: "💧",
  },
  EXERCISE: {
    label: "Movement",
    text: "text-exercise",
    bg: "bg-exercise",
    soft: "bg-exercise-soft",
    icon: "🏃",
  },
} as const;

export type StreamKey = keyof typeof STREAM_STYLE;

export function TypeBadge({ type }: { type: string }) {
  const s = STREAM_STYLE[type as StreamKey] ?? STREAM_STYLE.MEAL;
  return (
    <span className={`chip ${s.soft} ${s.text}`}>
      <span aria-hidden>{s.icon}</span>
      {s.label}
    </span>
  );
}

export function ProgressBar({
  value,
  tone = "bg-brand",
  className = "",
}: {
  value: number;
  tone?: string;
  className?: string;
}) {
  const v = Math.max(0, Math.min(100, value));
  return (
    <div
      className={`h-2 w-full overflow-hidden rounded-full bg-line ${className}`}
      role="progressbar"
      aria-valuenow={Math.round(v)}
      aria-valuemin={0}
      aria-valuemax={100}
    >
      <div
        className={`h-full rounded-full transition-[width] duration-500 ${tone}`}
        style={{ width: `${v}%` }}
      />
    </div>
  );
}

export function StatTile({
  label,
  value,
  sub,
  tone = "bg-brand",
  pct,
}: {
  label: string;
  value: ReactNode;
  sub?: ReactNode;
  tone?: string;
  pct?: number;
}) {
  return (
    <div className="card p-4">
      <p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p>
      <p className="mt-1.5 text-2xl font-bold tabular-nums">{value}</p>
      {pct !== undefined && <ProgressBar value={pct} tone={tone} className="mt-2.5" />}
      {sub && <p className="mt-2 text-xs leading-relaxed text-muted">{sub}</p>}
    </div>
  );
}

/** Circular adherence gauge — the headline number on the dashboard. */
export function AdherenceRing({
  pct,
  size = 132,
  label = "adherence",
}: {
  pct: number;
  size?: number;
  label?: string;
}) {
  const v = Math.max(0, Math.min(100, pct));
  const stroke = 12;
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = v >= 80 ? "var(--brand)" : v >= 55 ? "var(--warn)" : "var(--danger)";

  return (
    <div className="relative" style={{ width: size, height: size }}>
      <svg width={size} height={size} role="img" aria-label={`${v}% ${label}`}>
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke="var(--line)"
          strokeWidth={stroke}
        />
        <circle
          cx={size / 2}
          cy={size / 2}
          r={r}
          fill="none"
          stroke={color}
          strokeWidth={stroke}
          strokeLinecap="round"
          strokeDasharray={`${(v / 100) * circ} ${circ}`}
          transform={`rotate(-90 ${size / 2} ${size / 2})`}
          style={{ transition: "stroke-dasharray 600ms ease" }}
        />
      </svg>
      <div className="absolute inset-0 grid place-items-center text-center">
        <div>
          <p className="text-[26px] font-bold leading-none tabular-nums">{Math.round(v)}%</p>
          <p className="mt-1 text-[11px] font-medium uppercase tracking-wide text-muted">
            {label}
          </p>
        </div>
      </div>
    </div>
  );
}

export function SectionTitle({
  title,
  hint,
  right,
}: {
  title: string;
  hint?: string;
  right?: ReactNode;
}) {
  return (
    <div className="mb-3 flex flex-wrap items-end justify-between gap-2">
      <div>
        <h2 className="text-lg font-bold tracking-tight">{title}</h2>
        {hint && <p className="mt-0.5 text-sm text-muted">{hint}</p>}
      </div>
      {right}
    </div>
  );
}

export function AIBadge({ generatedBy }: { generatedBy: string }) {
  const isAI = generatedBy === "ai";
  return (
    <span
      className={`chip ${isAI ? "bg-brand-soft text-brand-strong" : "bg-warn-soft text-warn"}`}
      title={
        isAI
          ? "Generated by the AI planner"
          : "The model call did not succeed — this came from the built-in rule-based planner"
      }
    >
      {isAI ? "✦ AI generated" : "⚙ Rule-based fallback"}
    </span>
  );
}

export function EmptyState({
  title,
  body,
  action,
}: {
  title: string;
  body: string;
  action?: ReactNode;
}) {
  return (
    <div className="card grid place-items-center p-10 text-center">
      <div className="max-w-md">
        <h3 className="text-base font-bold">{title}</h3>
        <p className="mt-1.5 text-sm leading-relaxed text-muted">{body}</p>
        {action && <div className="mt-4 flex justify-center">{action}</div>}
      </div>
    </div>
  );
}
